---
title: "Ps07_extra_dis_dist"
author: "fk506cni"
date: "2023/3/7"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r}
require(DBI)
require(dbplyr)
require(RPostgreSQL)
require(tidyverse)
require(openxlsx)
require(DT)
require(tictoc)
require(jsonlite)
require(glue)
require(parallel)
```

```{r}
f_l <- "../dat4all/authdat/sec_l.json"
# f_r <- "../dat4all/authdat/sec.json"
```

```{r}
f2con <- function(f_json){
  dic <- jsonlite::read_json(f_json)
  host <- dic$host
  port <- dic$port
  user <- dic$user
  password <- dic$password
  dbname <- dic$dbname
  
  # dic
  con <- DBI::dbConnect(RPostgres::Postgres(),
                        host=host,
                        port=port,
                        user=user,
                        password = password,
                        dbname=dbname)
  
  return(con)
}

con <- f2con(f_l)
```


```{r}
f_iy <- "~/dat/tools/20230201/df_sy_master_share_20220922.xlsx"
f_iyb <- "~/dat/tools/20230201/df_sy_aborted_master_share_20220922.xlsx"
dfi <- read.xlsx(f_iy)
# %>% 
#   dplyr::filter(pick_check != 0)
dfia <- read.xlsx(f_iyb) 
# %>% 
#   dplyr::filter(pick_check != 0)

dfia %>% dim()

dfi_lv <- dfi %>% 
  filter(str_detect(sy_base, "ウイルス性肝炎")) %>% 
  filter(!str_detect(sy_base, "ヘルペス|サイトメガロ"))  %>% 
  select(sy_code, sy_trans_code) %>%
  unlist()

dfia_lv <- dfia %>% 
  filter(str_detect(sy_base, "ウイルス性肝炎")) %>% 
  filter(!str_detect(sy_base, "ヘルペス|サイトメガロ")) %>% 
  select(sy_code, sy_trans_code) %>% 
  unlist()

code_hepatitis <- c(dfi_lv, dfia_lv) %>%
  .[!is.na(.)]


dfi <- dfi %>%
  dplyr::filter(pick_check != 0)
dfia <- read.xlsx(f_iyb) %>%
  dplyr::filter(pick_check != 0)
dfia %>% dim()

dfi %>% colnames()
df_y <- dfi %>% 
  dplyr::select(one_of(c("Col4Cat",
                         "pick_check",
                         "ICD10",
                         "sy_base",
                         "sy_code",
                         "sy_trans_code"))) %>% 
  dplyr::distinct() %>% 
  filter(str_detect(Col4Cat,"コロナウイルス")) %>% 
  filter(ICD10 =="U071")

covid_code  <- c(df_y$sy_code, df_y$sy_trans_code) %>% 
  unique() %>% 
  str_c(collapse =  "','")

covid_code
```

```{r}
arglist <- list()


kw2codes <- function(df,kw){
  df %>% 
    dplyr::filter(str_detect(Col4Cat, kw)) %T>% 
    print() %>% 
    select(sy_code, sy_trans_code) %>% 
    unlist() %>% 
    unique() %>% 
    str_c(collapse =  "','") %>%
    return()
}
#covid
arglist$covid_codes <- covid_code

# resp
# arglist$sars_codes <- kw2codes(dfi, "ＳＡＲＳ")
# arglist$mers_codes <- kw2codes(dfi, "ＭＥＲＳ")
arglist$infl_codes <- kw2codes(dfi, "^インフルエンザ")
arglist$rs_codes <- kw2codes(dfi, "ＲＳウイルス感染症")

# # mosk
# arglist$deng_codes <- kw2codes(dfi, "デング熱")
# arglist$jika_codes <- kw2codes(dfi, "ジカウイルス")
# arglist$chik_codes <- kw2codes(dfi, "チクングニア熱")
# 
# # hemo
# arglist$sftf_codes <- kw2codes(dfi, "重症熱性血小板減少症候群")
# arglist$evo_codes <- kw2codes(dfi, "エボラ出血熱")
# arglist$rassa_codes <- kw2codes(dfi, "ラッサ熱")
# 
# # entro
# arglist$entero_codes <- kw2codes(dfi, "エンテロウイルス")
# arglist$polio_codes <- kw2codes(dfi, "ポリオ")
# 
# # zoo
# arglist$saru_codes <- kw2codes(dfi, "サル痘")
# arglist$dani_codes <- kw2codes(dfi, "ダニ媒介性脳炎")
# arglist$kokushi_codes <- kw2codes(dfi, "コクシジオイデス症")
# arglist$tori_codes <- kw2codes(dfi, "鳥インフルエンザ")
# 
# # impo
# arglist$mara_codes <- kw2codes(dfi, "マラリア")
# arglist$inu_codes <- kw2codes(dfi, "狂犬病")
# 
# # bio
# arglist$hebi_codes <- kw2codes(dfi, "ヘビ毒")
# arglist$kumo_codes <- kw2codes(dfi, "クモ毒")
# 
# # other
# arglist$tanso_codes <- kw2codes(dfi, "炭疽")
# arglist$botu_codes <- kw2codes(dfi, "ボツリヌス症")
# arglist$pesto_codes <- kw2codes(dfi, "ペスト")
# arglist$adeno_codes <- kw2codes(dfi, "アデノウイルス感染症")
# arglist$mukinzui_codes <- kw2codes(dfi, "髄膜炎菌性髄膜炎")

# 
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
# _codes <- kw2codes(dfi, "xxx")
dis_set <- arglist %>% 
  names()
```



```{r}
# f_q <- "./re_sy_02.sql"

qq <- function(qfile, params = NULL, con = NULL){
  q_read <- qfile %>% 
    read_file() %>% 
    str_remove(., "^-- !preview conn=con\n") 
  if(is.null(params)){
    return(q_read)
  }else{
    params0 <- list(q_read)
    params_bind <- append(params0, params)
    params_bind$.con = con
    print(params_bind)
    do.call(glue_sql, params_bind) %>% 
    # glue_sql(q_read, .x= params,.con= con) %>% 
      return()
  }
}
# # read_file(f_q) %>% 
# #   str_remove(., "^-- !preview conn=con\n")
# 
# # qq(f_q)
# q_fix <- qq(qfile = f_q, params = arglist, con = con)
```

```{r}
qfa2df <- function(q_f, arglist, con){
  tic()
  q_fix <- qq(qfile = q_f, params = arglist, con = con)
  print(q_fix)
  res <- dbSendQuery(con, q_fix)
  
  df_0 <- data.frame()
  l_df <- list()
  chunksize <- 1e+4
  iternum <- 1
  while(!dbHasCompleted(res)){
    if(iternum %% 50 == 0){
      print(iternum)
    }
    df_i <- dbFetch(res, n = chunksize)
    # df_0 <- bind_rows(df_0, df_i)
    l_df[[iternum]] <- df_i
    # # l_df <- append(l_df, df_i)
    iternum <- iternum +1
  }
  dbClearResult(res)
  toc()
  
  # l_df <- bind_rows(l_df)
  l_df_ <- data.table::rbindlist(l_df)
  
  l_df_ %>% 
    dim() %>% 
    print()
  return(l_df_)
}
```


```{r}
qfa2Ex <- function(f, con, arglist){
  tic()
  tb <- arglist$tbl
  q_fix <- qq(qfile = f, params = arglist, con = con)
  print(q_fix)
  
  dbExecute(conn = con, statement = q_fix)
  
  toc()
}

get_ts <- function(){
  ts <- Sys.time() %>% 
    as.character() %>% 
    str_replace_all(" ", "_") %>% 
    str_replace_all("\\-|:", "")
  return(ts)
}

```

```{r}
df_grid <- readRDS("../dat4all/masters/ym_grid.rds") %>% 
  mutate(ym = as.character(ym))
df_grid %>% 
  DT::datatable()

yms <- df_grid$ym


df_proc <- expand.grid(yms = yms, dis = dis_set, stringsAsFactors = F)
```


```{r}

log_out <- function(i,l, tag, timing = NULL){
  if(is.null(l[["ym"]])){
    ym <- "9999"
  }else{
    ym <- l[["ym"]] %>% 
      as.character()
  }
  if(is.null(timing)){
    timing <- "start"
  }
  
  path_i <- paste("./logdir/","log_",
                  as.character(i),"_",
                  timing, "_",
                  ym, "_" ,
                  tag,"_",
                  get_ts(), ".json", collapse = "")
  jsonlite::write_json(x = l, path = path_i)
  
}


get_tabl <- function(i){
  # tagx <- "pand_disname"
  f_l <- "../dat4all/authdat/sec_l.json"
  con <- f2con(f_json = f_l)
  
  ym <- df_proc$yms[[i]]
  dis <- df_proc$dis[[i]]
  tagx <- dis
  arglist$discode <- arglist[[dis]]
  # ym <- yms[[i]]
  
  print(ym)
  print(dis)
  print(arglist$discode)
  arglist$ym <- ym
  
  log_out(i = i, l = arglist, tag = tagx)
  df_ym_i <-  qfa2df(q_f = f_, arglist = arglist, con = con)
  df_ym_i <- df_ym_i %>%
      mutate(yms = ym,
             dis = dis,
             file = f_)
  log_out(i = i, l = arglist, tag = tagx, timing = "end")
  f_out <- c("./res/several_dis_res_",as.character(i), "_", dis, "_", ym, "_",get_ts(), ".rds") %>% 
    str_c(., collapse = "")
  df_ym_i %>% 
    saveRDS(object = ., file = f_out)
  log_out(i = i, l = arglist, tag = tagx, timing = "end")
  
  gc(reset = T)
  gc(reset = T)
  
  return(df_ym_i)
}
# 
```

```{r}
f_pick_dis <- "./queries/pick_dis_func.sql"
qfa2Ex(f = f_pick_dis, con = con, arglist = arglist)
# 
# f_pick_dis <- "./queries/pick_disset_func.sql"
# qfa2Ex(f = f_pick_dis, con = con, arglist = arglist)
# 
# f_pick_dis2 <- "./queries/pick_disset_seq2_tbl.sql"
# qfa2Ex(f = f_pick_dis, con = con, arglist = arglist)
# 
# f_pick_dis_dual <- "./queries/pick_dis_func_dual.sql"
# qfa2Ex(f = f_pick_dis_dual, con = con, arglist = arglist)
# # f_pick_si <- "./queries/pick_si_func.sql"
# qfa2Ex(f = f_pick_si, con = con, arglist = arglist)

```



```{r}
# i <- 16
# ym <- yms[[i]]
# print(ym)
# arglist$ym <- ym
# 
# 
# 
# arglist$ym
# arglist$sars_codes
arglist

# f_ <- "./queries/dis_tabl_extra.sql"
f_ <- "./queries/dis_dist_any_wfunc2.sql"
# tic()
# res <- get_tabl(i)
# toc()
# # res

```

```{r}

```



```{r}
tic()

cl <- makeCluster(2)

clusterExport(cl, varlist = c("yms","df_proc" ,"arglist", "f_"),envir = environment())
clusterExport(cl, varlist = c("get_ts", "log_out", "f2con", "qfa2Ex", "qq","qfa2df", "get_tabl"),envir = environment())                              
                              
yy <- 1:length(df_proc$yms) 
# %>%
#   .[1:2]

clusterEvalQ(cl, {
  require(data.table)
  require(DBI)
  require(RPostgreSQL)
  require(tidyverse)
  require(tictoc)
  require(jsonlite)
  require(glue)

  
  })
clusterEvalQ(cl, get_tabl)
res <- parSapplyLB(cl = cl,
                 X = yy,
                 FUN = get_tabl,
                 simplify = F,chunk.size = 1)
stopCluster(cl)
toc()
```



```{r}
f_out <- c("./several_dis_res_",get_ts(), ".rds") %>% 
  str_c(., collapse = "")
f_out
res %>% 
  saveRDS(object = ., file = f_out)
```

```{r}
# res
```

```{r}
sessionInfo()
```

