---
title: "S231_yen2doller"
author: "fk506.cni"
date: "2023-07-19"
output: html_document
editor_options: 
  chunk_output_type: console
---

data obtained from

https://www.stat-search.boj.or.jp/ssi/mtshtml/fm08_m_1.html

2023/7/19



```{r}
require(tidyverse)
require(openxlsx)
require(DT)
require(tictoc)
require(data.table)
require(officer)
require(lubridate)
```


```{r}
outputdir <- "./figs/"
if(!dir.exists(outputdir)){
  dir.create(outputdir)
}

ggsave2_tri <- function(plot, wid = 9, hei=9){
  plot_name <- deparse(substitute(plot))
  
  #png
  file_name <- paste(outputdir,plot_name, ".png", sep = "",collapse = "")
  ggsave(filename = file_name,plot = plot,device = "png",width = wid, height = hei,dpi = 300,units = "cm")
  f2metajson(file_name)
  
  # #pdf
  # file_name <- paste(outputdir,plot_name, ".pdf", sep = "",collapse = "")
  # ggsave(filename = file_name,plot = plot,device = "pdf",width = wid, height = hei,dpi = 300,units = "cm")
  # f2metajson(file_name)
  
  #pptx
  file_name <- paste(outputdir,plot_name, ".pptx", sep = "",collapse = "")
  plot_ed <- rvg::dml(ggobj = plot,width = wid, height = hei)
  
  doc <- read_pptx() %>%
    add_slide('Title and Content', 'Office Theme') %>%
    ph_with(value = "", location = ph_location_type(type = "title")) %>%
    ph_with(value = plot_ed, location = ph_location(type = "body",width = cm2inch(wid), height = cm2inch(hei),left = 2, top = 2))
  doc %>%
    print(target = file_name)
  f2metajson(file_name)
  
}



inch2cm <- function(x){
  return(x/0.39370)
}
cm2inch <- function(x){
  return(0.39370*x)
}

p2cm <- function(x){
  return(as.integer(0.008466666666666667 * x))
}

cm2p <- function(x){
  return(as.integer(118.11023622047244 *x))
}

sv2ggkm <- function(svfit){
  p <- ggsurvplot(fit = svfit, data = df,
                risk.table.title = "risk.table.title", risk.table.y.text.col = TRUE,
           risk.table.y.text = FALSE, fontsize = 5,
           risk.table = TRUE, tables.theme = theme_pubr(), ggtheme = theme_pubr())
  p_km <- p$plot
  p_tb <- p$table
  p2 <- cowplot::plot_grid(p_km, p_tb, ncol = 1,align = "v", rel_heights = c(3,1))
  grid::grid.draw(p2)
  return(p2)
}


f2metajson <- function(f){
  l <- file.info(f) %>% as.list()
  l2 <- list()
  
  l2 <- list()
  l_names <- names(l)
  
  for (i in 1:length(l)){
    if(l_names[i] %in% c("uid", "gid", "mode", "uname", "grname")){
      # print(l_names[i])
    }else{
      if("POSIXct" %in% class(l[[i]])){
        l2[[l_names[i]]] <- l[[i]] %>% 
          lubridate::ymd_hms() %>% 
          as.character()
      }else{
        l2[[l_names[i]]] <- as.character(l[[i]])
      }
    }
  }
  
  l2$f <- f
  l2$md5 <- f %>% 
    file(.,open = "rb") %>% 
    openssl::md5() %>% 
    as.character() %>% 
    as.character()
  l2$sha256 <- f %>% 
    file(.,open = "rb") %>% 
    openssl::sha256() %>% 
    as.character() %>% 
    as.character()
  print(l2)
  f_json <- paste(f, ".json", sep="", collapse = "")
  jsonlite::write_json(x = l2, path = f_json, pretty=T, auto_unbox=T)
  # return(l2)
  # # jsonlite::write_json(x = l2, path = f_json)
}


get_ts <- function(){
  ts <- Sys.time() %>% 
    as.character() %>% 
    str_replace_all(" ", "_") %>% 
    str_replace_all("\\-|:", "")
  return(ts)
}


```



```{r}
ts <- get_ts()
ts
```

東京市場　ドル・円　スポット　17時時点/月末	東京市場　ドル・円　スポット　17時時点/月中平均	東京市場　ドル・円　スポット　中心相場/月末	東京市場　ドル・円　スポット　中心相場/月中平均	東京市場　ドル・円　スポット　月中最高値	東京市場　ドル・円　スポット　月中最安値


FM08'FXERM06[簡易グラフ]	FM08'FXERM07[簡易グラフ]	FM08'FXERM08[簡易グラフ]	FM08'FXERM09[簡易グラフ]	FM08'FXERM03[簡易グラフ]	FM08'FXERM05[簡易グラフ]

```{r}
cls <- c(
"ym",
"東京市場　ドル・円　スポット　17時時点/月末",	"東京市場　ドル・円　スポット　17時時点/月中平均",	"東京市場　ドル・円　スポット　中心相場/月末",	"東京市場　ドル・円　スポット　中心相場/月中平均",	"東京市場　ドル・円　スポット　月中最高値",	"東京市場　ドル・円　スポット　月中最安値"
) %>% 
  str_remove("東京市場　ドル・円　スポット　") %>% 
  str_replace("時時点/", "ocl_") %>% 
  str_replace("中心相場/", "cnt_") %>% 
  str_replace("月中", "mnt_") %>% 
  str_replace("月末", "end") %>% 
  str_replace("平均", "avg") %>% 
  str_replace("最高値", "hi") %>% 
  str_replace("最安値", "lw")
cls

f <- "./dat/fm08_m_1.csv"
# df_conv <- fread(f)
df_conv <- read.csv(f, header = F, encoding = "cp932", fill = T, skip=170,
                    col.names = cls) %>% 
  mutate(ym_num = ym %>% str_remove("/"))
```


```{r}
# f_cst <- "./dat/2022UR007_20230704/result_figs_tables/Ps002_hoko_dist/hoko_status_smr_20230704_104823.csv"

f_cst <- "./dat/2022UR007_20230721/datout_20230720/result_figs_tables/Ps002_hoko_dist/hoko_status_smr_20230721_091131.csv"

df_cst <- fread(f_cst) %>% 
  mutate(ym_num = as.character(ym_num),
         y = str_sub(ym_num, 1, 4))

df_conv_sub <- df_conv %>% 
  filter(ym_num %in% df_cst$ym_num) %>% 
  dplyr::select(ym_num, cnt_mnt_avg)

df_hk <- df_cst %>%
  left_join(df_conv_sub, by="ym_num") %>% 
  mutate(yen = 10 *sum_of_sum_total_score,
         doller = yen/cnt_mnt_avg)

# 
# df_hk %>% group_by(y) %>% 
#   summarise(yen = sum(yen))
```





```{r}
require(ggpubr)
require(officer)
p_cost_whole <- ggplot()+theme_pubr()+
  geom_line(data = df_hk,
            aes(x=mid_ym, y=doller, color=age_grade))+
  facet_wrap(~ categ, ncol = 1)

# p_cost_whole
```

```{r}
w1 <- 18
h1 <- 12

ggsave2_tri(p_cost_whole, wid = w1, hei = h1)
# ggsave2_tri(p_cost_whole)
```

```{r}
sessionInfo()
```

