---
title: "Ps003_S2_covid_pts_dist"
author: "fk506cni"
date: "2023/3/6"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
require(tidyverse)
require(openxlsx)
require(DT)
require(tictoc)
require(data.table)
require(officer)
require(lubridate)

require(openssl)
require(jsonlite)
```



From:  
https://covid19.mhlw.go.jp/  
https://www.mhlw.go.jp/stf/covid-19/open-data_english.html


```{r}
outputdir <- "./figs/"
if(!dir.exists(outputdir)){
  dir.create(outputdir)
}

ggsave2_tri <- function(plot, wid = 9, hei=9){
  plot_name <- deparse(substitute(plot))
  
  #png
  file_name <- paste(outputdir,plot_name, ".png", sep = "",collapse = "")
  ggsave(filename = file_name,plot = plot,device = "png",width = wid, height = hei,dpi = 300,units = "cm")
  f2metajson(file_name)
  
  #pdf
  file_name <- paste(outputdir,plot_name, ".pdf", sep = "",collapse = "")
  ggsave(filename = file_name,plot = plot,device = "pdf",width = wid, height = hei,dpi = 300,units = "cm")
  f2metajson(file_name)
  
  #pptx
  file_name <- paste(outputdir,plot_name, ".pptx", sep = "",collapse = "")
  plot_ed <- rvg::dml(ggobj = plot,width = wid, height = hei)
  
  doc <- read_pptx() %>%
    add_slide('Title and Content', 'Office Theme') %>%
    ph_with(value = "", location = ph_location_type(type = "title")) %>%
    ph_with(value = plot_ed, location = ph_location(type = "body",width = cm2inch(wid), height = cm2inch(hei),left = 2, top = 2))
  doc %>%
    print(target = file_name)
  f2metajson(file_name)
  
}



inch2cm <- function(x){
  return(x/0.39370)
}
cm2inch <- function(x){
  return(0.39370*x)
}

p2cm <- function(x){
  return(as.integer(0.008466666666666667 * x))
}

cm2p <- function(x){
  return(as.integer(118.11023622047244 *x))
}

sv2ggkm <- function(svfit){
  p <- ggsurvplot(fit = svfit, data = df,
                risk.table.title = "risk.table.title", risk.table.y.text.col = TRUE,
           risk.table.y.text = FALSE, fontsize = 5,
           risk.table = TRUE, tables.theme = theme_pubr(), ggtheme = theme_pubr())
  p_km <- p$plot
  p_tb <- p$table
  p2 <- cowplot::plot_grid(p_km, p_tb, ncol = 1,align = "v", rel_heights = c(3,1))
  grid::grid.draw(p2)
  return(p2)
}


f2metajson <- function(f){
  l <- file.info(f) %>% as.list()
  l2 <- list()
  
  l2 <- list()
  l_names <- names(l)
  
  for (i in 1:length(l)){
    if(l_names[i] %in% c("uid", "gid", "mode", "uname", "grname")){
      # print(l_names[i])
    }else{
      if("POSIXct" %in% class(l[[i]])){
        l2[[l_names[i]]] <- l[[i]] %>% 
          lubridate::ymd_hms() %>% 
          as.character()
      }else{
        l2[[l_names[i]]] <- as.character(l[[i]])
      }
    }
  }
  
  l2$f <- f
  l2$md5 <- f %>% 
    file(.,open = "rb") %>% 
    openssl::md5() %>% 
    as.character() %>% 
    as.character()
  l2$sha256 <- f %>% 
    file(.,open = "rb") %>% 
    openssl::sha256() %>% 
    as.character() %>% 
    as.character()
  print(l2)
  f_json <- paste(f, ".json", sep="", collapse = "")
  jsonlite::write_json(x = l2, path = f_json, pretty=T, auto_unbox=T)
  # return(l2)
  # # jsonlite::write_json(x = l2, path = f_json)
}
```

```{r}
# 
# f2metajson <- function(f){
#   l <- file.info(f) %>% as.list()
#   l2 <- list()
#   
#   l2 <- list()
#   l_names <- names(l)
#   
#   for (i in 1:length(l)){
#     if(l_names[i] %in% c("uid", "gid", "mode", "uname", "grname")){
#       # print(l_names[i])
#     }else{
#       if("POSIXct" %in% class(l[[i]])){
#         l2[[l_names[i]]] <- l[[i]] %>% 
#           lubridate::ymd_hms() %>% 
#           as.character()
#       }else{
#         l2[[l_names[i]]] <- as.character(l[[i]])
#       }
#     }
#   }
#   
#   l2$f <- f
#   l2$md5 <- f %>% 
#     file(.,open = "rb") %>% 
#     openssl::md5() %>% 
#     as.character() %>% 
#     as.character()
#   l2$sha256 <- f %>% 
#     file(.,open = "rb") %>% 
#     openssl::sha256() %>% 
#     as.character() %>% 
#     as.character()
#   f_json <- paste(f, ".json", sep="", collapse = "")
#   jsonlite::write_json(x = l2, path = f_json, pretty=T, auto_unbox=T)
#   # return(l2)
#   # # jsonlite::write_json(x = l2, path = f_json)
# }
# f <- "./figs/p_pts_1.pdf"
# f2metajson(f)
# l3 <- f %>% 
#   f2metajson()
# l3 %>% 
#   jsonlite::write_json(x = ., path = "./test.json", pretty=T, auto_unbox=T)
# l3$md5 %>% class()
# # %>% 
# #   as.character() %>% class()
```


```{r}
# f_rds <- "./covid_pts_res_20230306_131443.rds"
# f_rds <- "./covid_pts_res_20230313_211737.rds"
f_rds <- "./covid_pts_res_20230602_203424.rds"
df <- readRDS(f_rds) %>% 
  bind_rows() %>% 
  tidyr::complete(had_covid_bool, age_grade, yms,file,  fill = list(unique_id1n_count = 0))


# df %>% group_by(had_covid_bool) %>% 
#   summarise(n=sum(unique_id1n_count))
```




```{r}
f <- "../S148_covid_dis_timeseries/dat/newly_confirmed_cases_daily.csv"
df_ <- fread(f) %>% 
  mutate(dt = lubridate::ymd(Date),
         mt = lubridate::month(dt),
         yr = lubridate::year(dt),
         mid_ym = lubridate::make_date(yr, mt, "15")) %>% 
  select(dt,mt,yr,mid_ym, everything())

# df_ %>% 
#   DT::datatable()

df_smr <- df_ %>% 
  group_by(mid_ym) %>% 
  summarise(n_pts=sum(ALL)) %>% 
  mutate(categ = "new_patients_from_hersys")

# df_smr %>% 
#   DT::datatable()
```

```{r}

df_rc <- df %>% 
  group_by(had_covid_bool, yms,file) %>% 
  summarise(unique_id1n_count = sum(unique_id1n_count)) %>% 
  mutate(mid_ym = str_c(yms, "15", sep="") %>% 
           lubridate::ymd()) %>% 
  mutate(n_pts= unique_id1n_count,
         categ = ifelse(had_covid_bool ==1, 
                        "rece_id_with_covid_diagnosis",
                        "rece_id_without")) %>% 
  select(mid_ym, n_pts, categ)
# 
# df_rc %>%
#   filter(categ=="rece_id_with_covid_diagnosis") %>% 
#   .[["n_pts"]] %>% 
#   sum()
# 
# df_rc %>%
#   filter(categ=="rece_id_without") %>% 
#   .[["n_pts"]] %>% 
#   sum()
```

```{r}
df_vis <- bind_rows(df_rc,
                    df_smr)
# df_vis %>% summary()
require(ggpubr)

p_pts <- ggplot()+theme_pubr(legend = "right")+
  geom_line(data = df_vis,
            aes(x = mid_ym, y = n_pts+1, color=categ))+
  scale_y_log10()
# p_pts

ggsave2_tri(p_pts, wid = 20, hei=10)

```

```{r}
get_ts <- function(){
  ts <- Sys.time() %>% 
    as.character() %>% 
    str_replace_all(" ", "_") %>% 
    str_replace_all("\\-|:", "")
  return(ts)
}
ts <- get_ts()
ts
f_out <- c("./pts_dist_3_", ts, ".csv") %>% 
  str_c(collapse = "")
f_out

write.csv(x = df_vis, file = f_out,quote = T, row.names = T)


# df_test <- fread(f_out)
```

```{r}
f_each_out <- c("./pts_dist_each_", ts, ".csv") %>% 
  str_c(collapse = "")
f_each_out 

write.csv(x = df, file = f_each_out,quote = T, row.names = T)

```


```{r}
df_vis_1 <- bind_rows(df_rc %>% dplyr::filter(categ != "rece_id_without")
                        ,df_smr) %>% 
  mutate(n_pts = as.numeric(n_pts))
# df_vis_1
# df_vis_1 %>% 
#   DT::datatable()

p_pts_1 <- ggplot()+theme_pubr(legend = "right")+
  geom_line(data = df_vis_1,
            aes(x = mid_ym, y = n_pts, color=categ)) +
  scale_y_continuous()
# p_pts_1
ggsave2_tri(p_pts_1, wid = 20, hei=10)
```

```{r}
df_vis_2 <- df %>% 
  mutate(mid_ym = str_c(yms, "15", sep="") %>% 
           lubridate::ymd()) %>% 
  mutate(n_pts= unique_id1n_count %>% 
           as.numeric(),
         categ = ifelse(had_covid_bool ==1, 
                        "rece_id_with_covid_diagnosis",
                        "rece_id_without")) %>% 
  filter(had_covid_bool ==1)

p_pts_age <- ggplot()+theme_pubr(legend = "right")+
  geom_line(data = df_vis_2,
            aes(x = mid_ym, y = n_pts, color=age_grade)) +
  scale_y_continuous()
# p_pts_age


ggsave2_tri(p_pts_age, wid = 20, hei=10)
```



```{r}
sessionInfo()
```

