---
title: "S234_wave_definition"
author: "fk506.cni"
date: "2023-07-19"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
require(tidyverse)
require(openxlsx)
require(DT)
# require(parallel)
require(data.table)
require(officer)
```


```{r}
outputdir <- "./figs/"
if(!dir.exists(outputdir)){
  dir.create(outputdir)
}

ggsave2_tri <- function(plot, wid = 9, hei=9){
  plot_name <- deparse(substitute(plot))
  
  #png
  file_name <- paste(outputdir,plot_name, ".png", sep = "",collapse = "")
  ggsave(filename = file_name,plot = plot,device = "png",width = wid, height = hei,dpi = 300,units = "cm")
  f2metajson(file_name)
  
  #pdf
  # file_name <- paste(outputdir,plot_name, ".pdf", sep = "",collapse = "")
  # ggsave(filename = file_name,plot = plot,device = "pdf",width = wid, height = hei,dpi = 300,units = "cm")
  # f2metajson(file_name)
  
  #pptx
  file_name <- paste(outputdir,plot_name, ".pptx", sep = "",collapse = "")
  plot_ed <- rvg::dml(ggobj = plot,width = wid, height = hei)
  
  doc <- read_pptx() %>%
    add_slide('Title and Content', 'Office Theme') %>%
    ph_with(value = "", location = ph_location_type(type = "title")) %>%
    ph_with(value = plot_ed, location = ph_location(type = "body",width = cm2inch(wid), height = cm2inch(hei),left = 2, top = 2))
  doc %>%
    print(target = file_name)
  f2metajson(file_name)
  
}



inch2cm <- function(x){
  return(x/0.39370)
}
cm2inch <- function(x){
  return(0.39370*x)
}

p2cm <- function(x){
  return(as.integer(0.008466666666666667 * x))
}

cm2p <- function(x){
  return(as.integer(118.11023622047244 *x))
}

sv2ggkm <- function(svfit){
  p <- ggsurvplot(fit = svfit, data = df,
                risk.table.title = "risk.table.title", risk.table.y.text.col = TRUE,
           risk.table.y.text = FALSE, fontsize = 5,
           risk.table = TRUE, tables.theme = theme_pubr(), ggtheme = theme_pubr())
  p_km <- p$plot
  p_tb <- p$table
  p2 <- cowplot::plot_grid(p_km, p_tb, ncol = 1,align = "v", rel_heights = c(3,1))
  grid::grid.draw(p2)
  return(p2)
}


f2metajson <- function(f){
  l <- file.info(f) %>% as.list()
  l2 <- list()
  
  
  l_names <- names(l)
  
  for (i in 1:length(l)){
    if(l_names[i] %in% c("uid", "gid", "mode", "uname", "grname")){
      # print(l_names[i])
    }else{
      if("POSIXct" %in% class(l[[i]])){
        l2[[l_names[i]]] <- l[[i]] %>% 
          lubridate::ymd_hms() %>% 
          as.character()
      }else{
        l2[[l_names[i]]] <- as.character(l[[i]])
      }
    }
  }
  
  l2$f <- f
  l2$md5 <- f %>% 
    file(.,open = "rb") %>% 
    openssl::md5() %>% 
    as.character() %>% 
    as.character()
  l2$sha256 <- f %>% 
    file(.,open = "rb") %>% 
    openssl::sha256() %>% 
    as.character() %>% 
    as.character()
  print(l2)
  f_json <- paste(f, ".json", sep="", collapse = "")
  jsonlite::write_json(x = l2, path = f_json, pretty=T, auto_unbox=T)
  # return(l2)
  # # jsonlite::write_json(x = l2, path = f_json)
}
```


```{r}
f_smr <- "./dat/2022UR007_20230706/result_figs_tables/Ps003_covid_pts_dist/pts_dist_3_20230706_143353.csv"
df_smr <- fread(f_smr) %>% 
  mutate(category = 
           case_when(
             categ == "rece_id_with_covid_diagnosis" ~ "From NDB",
             categ == "new_patients_from_hersys" ~ "From HER-SYS",
             categ == "rece_id_without" ~ "Without COVID-19\nFrom NDB"
           ))
```

April 2020
August 2020
January 2021
May 2021
August 2021
February 2022
August 2022


```{r}
peaks <- c("2020-04-15", 
           "2020-08-15",
           "2021-01-15",
           "2021-05-15",
           "2021-08-15",
           "2022-02-15",
           "2022-08-15")

peaks_n <- c(
"1st",
"2nd",
"3rd",
"4th",
"5th",
"6th",
"7th"
)

df_peaks <- df_smr %>% 
  filter(categ == "rece_id_with_covid_diagnosis") %>% 
  filter(mid_ym %in% lubridate::ymd(peaks)) %>% 
  mutate(wave_num = peaks_n)


df_peaks %>% write.xlsx(file = "./peaks.xlsx")


```


```{r}
require(ggpubr)
require(ggrepel)

h <- 9
w <- 18

p_pts_2 <- ggplot()+theme_pubr(legend = "right")+
  geom_line(data = df_smr %>% 
              filter(categ != "rece_id_without"),
            aes(x = mid_ym, y = n_pts, color=category)) +
  geom_point(data = df_peaks,
             aes(x = mid_ym, y = n_pts), color="black")+
  geom_text_repel(
    data = df_peaks,
    aes(x = mid_ym, y = n_pts, label= wave_num),
    min.segment.length = 0,
    box.padding = 0.9,
    # max.overlaps = Inf,
    segment.size = 0.2 ,seed = 1234, vjust = "top"
  )+
  # scale_y_log10()+
  scale_y_continuous()+
  # coord_cartesian(expand = F)+
  xlab("years")+ylab("Number of Patients")

# p_pts_2


ggsave2_tri(p_pts_2, wid =w, hei = h)
```



```{r}
p_pts <- ggplot()+theme_pubr(legend = "right")+
  geom_line(data = df_smr,
            aes(x = mid_ym, y = n_pts+1, color=categ))+
  scale_y_log10()+
    geom_point(data = df_peaks,
             aes(x = mid_ym, y = n_pts+1), color="black")+
  geom_text_repel(
    data = df_peaks,
    aes(x = mid_ym, y = n_pts+1, label= wave_num),
    min.segment.length = 0,
    box.padding = 0.9,
    # max.overlaps = Inf,
    segment.size = 0.2 ,seed = 1234, vjust = "top"
  )+
  xlab("years")+ylab("Number of Patients +1")

# p_pts

ggsave2_tri(p_pts, wid =w, hei = h)
```


```{r}
sessionInfo()
```

